// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blfixkhgzwxxomdydzmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsZml4a2hnend4eG9tZHlkem1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzM5OTAsImV4cCI6MjA2Mjk0OTk5MH0.ApFmv5A-Q8pIleSFYNhAyW3hd9x7afSJuEcnyfUQsKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);